name: packaroo
description: "A modern Flutter desktop application for packaging Java applications with jpackage and jlink."
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  material_symbols_icons: ^4.2719.3
  animated_text_kit: ^4.2.2
  lottie: ^3.1.2
  
  # File Management
  file_picker: ^8.1.4
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Process Management
  process_run: ^1.2.0
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  
  # Desktop Integration
  window_manager: ^0.3.7
  desktop_drop: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  
  # Linting
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    # - assets/animations/
    - assets/icons/

flutter_launcher_icons:
  android: false
  ios: false
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"
  linux:
    generate: true
    image_path: "assets/icons/icon.png"
